# Site settings
title: Portfolio - Tisha Greenidge
email: tisha.m.greenidge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer specializing in JavaScript, Angular, Nodejs, Express, HTML, CSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tgreenidge.com" # the base hostname & protocol for your site
twitter_username: nav_grl_onrails
github_username:  tgreenidge
linkedin_username: tishagreenidge

permalink: /:categories/:title
links:
  - title: about
    url: /about
  - title: projects
    url: /work
  - title: blog
    url: /blog
  # - title: hire me
  #   url: /resume

# Build settings
markdown: kramdown

